### ISSUE TITLE
README should include advice on creating a reprex

### ISSUE THREAD

**Issue by hadley** [jennybc/reprex#13]
Because I think this package will soon be the top google hit for reprex

**Comment by jennybc** [comment]
You mean the conceptual stuff? I tried to dodge that by linking to existing material but looks like I've not those links obvious enough or I can't pass the buck so easily.

**Comment by jennybc** [comment]
The section I'm referring to is [Reproducible Examples](https://github.com/jennybc/reprex#reproducible-examples).

**Comment by hadley** [comment]
I think it would be even better to inline some of that advice. Long readmes are all the rage these days!
