### ISSUE TITLE
Make an RStudio add in

### ISSUE THREAD

**Issue by hadley** [jennybc/reprex#28]
http://rstudio.github.io/rstudioaddins/

I think the nicest implementation would replace the currently selected code with the reprexed version. To make it work if called multiple times, you could first strip any lines that start with `#'` (maybe reprex already does this?)

**Comment by jennybc** [comment]
By "strip any lines that start with `#'`", do you mean what I mean in https://github.com/jennybc/reprex/issues/27? I.e. be able to cycle between just the code and the reprexed version of it? I think I also have to strip off any enclosing backtick lines and, in the case of SO, the `<!-- language: lang-r -->` line, yes?

Are you saying to do this instead of or in addition to putting the reprexed version on the clipboard?

**Comment by hadley** [comment]
I was thinking of replacing the currently selected code instead of putting it on the clipboard, so it wouldn't have the backticks.

**Comment by jennybc** [comment]
If you have occasion to use reprex, you could re-install and try the draft addin.

I am still NOT replacing the reprex source with the output, although I experimented with that and could still do it. I now have the ability to do round trips (code --> rendered reprex --> code), which would be useful.

Overwriting or augmenting the source with the reprexed result caused me more grief than joy, but I think we must use this thing differently? I like seeing the html preview and having the GitHub-flavored markdown on the clipboard.

I think what you want ("strip lines that start with `#'`", no backticks, etc.) might be related to #32, which is about going from `.R` to `.R` but with commented-out output?

**Comment by MilesMcBain** [comment]
Another reason to go with Hadley's suggestion is that `reprex` would work nicely on RStudio server.

**Comment by jennybc** [comment]
Thanks @MilesMcBain this is a helpful use case, when it would be nice for the rendered reprex to be inserted into or on top of the current file.

As for DISPLAY, yes, that must be configured for clipboard to work (see `.travis.yml`).

> ... and use clipr::write_clip() I might be able to then build the reprex and then obtain the result using clipr::read_clip(). A bit convoluted though.

Once you get the clipboard working at all, reprex takes care of all this for you, i.e. you would never need to explicitly call clipr.

**Comment by jennybc** [comment]
From @hadley:

> confirmation dialog ("reprex ready on clipboard") is a bit too assertive

I should either remove this or figure out how to make the message simply disappear after some suitable interval.

**Comment by jennybc** [comment]
Thx @hadley and @daattali, I think current addin now counts as "existing"!

@MilesMcBain The more I think about this, you should never get that error. reprex should detect the lack of clipboard and give you a better message about where to find the output. Are you sure you were using a very recent version? If so, will you open that as a separate issue about RStudio Server?
