### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by sckott** [jennybc/reprex#3]
in your readme

> In theory, this is the domain of gistr, but people also tend to post .R or .Rmd and NOT resulting .md ... is there a gap in tools or is this just an unfortunate behavior pattern? I don't always want to render these files to see what someone's trying to show me.

but a `.R` or `.Rmd` file can go up un-rendered via `gist_create()` if you do `knit=FALSE` (which is the default)

**Comment by jennybc** [comment]
But I'm making the opposite point: I wish the default when someone posts `.R` or `.Rmd` is to knit the darn thing locally and post resulting `.md` in the same gist (with figs, if necessary). Everytime someone posts `.R` or `.Rmd` only I'm like ... so I'm supposed to grab this gist and run it? Can't you do that for me? :grin:

**Comment by sckott** [comment]
ah! I see, sorry about that.  right, okay, closing
