### ISSUE TITLE
Generate .R output files

### ISSUE THREAD

**Issue by noamross** [jennybc/reprex#32]
Per [this twitter discussion](https://twitter.com/noamross/status/742710818534522880), it would be useful to be able to generate an output .R file that is runnable but has outputs stored in comments.

One slight difference in the output will be that image links would have to be commented.

**Comment by jennybc** [comment]
So is something simple going to be OK? Such as ... proceed as if the target venue is GitHub. But then

  * Protect anything not inside an R chunk with a comment prefix. This could be an image link or text that originated in a roxygen comment.
  * Remove all instances of <code>``` r</code> and <code>``` r</code>.

Can you think of anything else?

**Comment by noamross** [comment]
Makes sense to me

**Comment by jennybc** [comment]
And were you thinking such a `.R` in addition to the markdown or instead of? Is the production of this output-enhanced R script a primary goal or a useful by-product?

**Comment by noamross** [comment]
Instead of. An output-enhanced R script is what I'm looking for as the
primary goal.  Essentially, it should do exactly what the script I input
does, but have comments showing the expected output.

**Comment by jennybc** [comment]
@noamross 

Will you try this out? Is it wanted you wanted?

```r
devtools::install_github("jennybc/reprex")
library(reprex)
x <- reprex({
  #' Some prose
  ## regular comment
  (x <- 1:4)
  median(x)
  plot(1:5)
}, venue = "R", outfile = "noam")
##readLines("noam_rendered.R")
## is 'noam_rendered.R' what you had in mind?

```

**Comment by noamross** [comment]
Yes, this is what I was looking for.  Nice error message for catching re-rendered code!

**Comment by jennybc** [comment]
> Nice error message for catching re-rendered code!

I'm glad someone noticed ☺️. And glad the overall thing looks about right.
