### ISSUE TITLE
Add comment character parameter

### ISSUE THREAD

**Issue by alistaire47** [jennybc/reprex#33]
Currently, if I run

``` r
reprex::reprex({x <- rnorm(100) ; mean(x)}, venue = 'gh', show = FALSE)
```

I get the code for

``` r
x <- rnorm(100)
mean(x)
#> [1] 0.06771625
```

which is wonderful! However, changing the comment character, e.g.  to `##` is more complicated, requiring (as suggested [on Twitter](https://twitter.com/JennyBryan/status/774992183233421312)) copying

``` r
#+ include=FALSE
knitr::opts_chunk$set(comment = '##')

#+ realstuff
x <- rnorm(100)
mean(x)
```

and then calling `reprex::reprex()` to get the code for

``` r
x <- rnorm(100)
mean(x)
## [1] 0.04698201
```

To make this process simpler, could we get a comment character parameter in `reprex` akin to `formatR::tidy_eval`'s `prefix`?

**Comment by jennybc** [comment]
OK you can do this now like so:

``` r
reprex::reprex({x <- rnorm(100) ; mean(x)}, venue = 'gh',
               opts_chunk = list(comment = '##'))
```

That generates this:

``` r
x <- rnorm(100) ; mean(x)
## [1] -0.04785671
```

This can be used to provide general knitr chunk and package options and, in particular, the one you wanted to modify.
