### ISSUE TITLE
Re-indenting source

### ISSUE THREAD

**Issue by jennybc** [jennybc/reprex#36]
I'm about push something that changes how expression input is converted to a character vector. The leading whitespace can be suboptimal. To be clear, I'm not sure this is really new. The previous expression handling probably also mangled whitespace, just in a different way.

Bottom line: given source in a character vector or file, is there a way to re-indent it nicely?

@jimhester do you know?

**Comment by jennybc** [comment]
Example. This call:

``` r
reprex({
 x <- 1:4
 y <- 2:5
 x + y
})
```

gives rise to this:

``` r
 x <- 1:4
 y <- 2:5
x + y
#> [1] 3 5 7 9
```

Code that started out evenly indented is no longer so. Maybe I could be more respectful of whitespace when turning expression input into strings? But it would be much easier if there was a way to just re-indent.

**Comment by jennybc** [comment]
Perhaps a job for `formatR::tidy_source()`.

http://yihui.name/formatR/

**Comment by jennybc** [comment]
Fixed in 96f065ab9fc1e796aa7d2c3cebb59b2359bfbb1e.

**Comment by jimhester** [comment]
I think just using `format()` on the quoted expression would work fine actually, no need for the extra dependency. FWIW it would be nice if `reprex()` also accepted a pre-formatted string directly, like you get from `clipr::read_clip()`.

``` r
ex <- quote({
 x <- 1:4
 y <- 2:5
 x + y
})

cat(as.character(ex), sep = "\n")
#> {
#> x <- 1:4
#> y <- 2:5
#> x + y
cat(format(ex), sep = "\n")
#> {
#>     x <- 1:4
#>     y <- 2:5
#>     x + y
#> }
```

**Comment by jennybc** [comment]
reopening so I remember to try what you say @jimhester

**Comment by jennybc** [comment]
OK yes `format()` is not perfect, but it's better than nothing. formatR is a suggested package (which is already true via the knitr dependency anyway). If formatR is not available, then `format()` is applied to the expression, once it has been captured as a character vector.

Here's how it does with a well-formatted expression. `reprex()` call (example from above):

``` r
reprex({
  x <- 1:4
  y <- 2:5
  x + y
})
```

Output:

``` r
x <- 1:4
y <- 2:5
x + y   
#> [1] 3 5 7 9
```

And an expression with more pathological formatting. `reprex()` call:

``` r
reprex({
  x <- 1:10
  for (i in x) {
            print(i)
}
  x
})
```

Output:

``` r
x <- 1:10     
for (i in x) {
print(i)      
}             
#> [1] 1
#> [1] 2
#> [1] 3
#> [1] 4
#> [1] 5
#> [1] 6
#> [1] 7
#> [1] 8
#> [1] 9
#> [1] 10
x             
#>  [1]  1  2  3  4  5  6  7  8  9 10
```
