### ISSUE TITLE
Build matrix in Travis to test DISPLAY envvar

### ISSUE THREAD

**Issue by mdlincoln** [jennybc/reprex#45]
Given that, for CRAN prep, it's useful to know that your package will pass even when the clipboard is not available, I've simulated this on Travis using a [build matrix](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix)

<https://github.com/mdlincoln/clipr/blob/93329a6d96ae6fd00cb0d920f5b861b482b56ae8/.travis.yml>

This should run tests both with and without `DISPLAY` being configured properly.

**Comment by jennybc** [comment]
Excellent idea! Will adopt.
