### ISSUE TITLE
Which R version is really needed?

### ISSUE THREAD

**Issue by jennybc** [jennybc/reprex#5]
@muschellij2 correctly [pointed out on twitter](https://twitter.com/StrictlyStat/status/636604468319100928) that current R version is probably unnecessarily high.

Roll this back and see what happens? Possible version: 3.0.2, which he proposed because it's what CRAN devtools requires.

**Comment by jennybc** [comment]
I don't think the above commit really addresses this -- possible the wrong issue was tagged?

**Comment by muschellij2** [comment]
Agreed
