### ISSUE TITLE
paste reprex as folded block?

### ISSUE THREAD

**Issue by jayhesselberth** [jennybc/reprex#54]
It would be nice to be able to paste a reprex into a github issue as a [folded block](http://stackoverflow.com/questions/32814161/how-to-make-spoiler-text-in-github-wiki-pages/39920717#39920717).

The HTML is a little tricky to get right, but this could be addressed by incorporating it on the reprex side. I was thinking something like:

```r
reprex(venue = 'gh', folded = TRUE)
```

Would you consider a PR?

**Comment by jennybc** [comment]
I use this already for the optional session info.

In fact, because html is passed through, you can already achieve this.

If this is input to `reprex()`:

```r
#'<details><summary>`reprex!`</summary>
(x <- 1:4)
median(x)
#'</details>
```

It becomes this once pasted in here:

<details><summary>`reprex!`</summary>

``` r
(x <- 1:4)
#> [1] 1 2 3 4
median(x)
#> [1] 2.5
```

</details>


But I could make it even easier, I suppose.

**Comment by jayhesselberth** [comment]
Great, didn't know that worked without the `<p>` tags, which were the tricky part.

"Even easier" would be not having to remember all the HTML bits.

**Comment by jennybc** [comment]
It feels like it should be something you could apply to a knitr chunk. For a simple reprex, that is one chunk, you could fold your whole reprex this way. But for a bigger reprex, you might want to fold just one particularly hairy piece, for example. Then what I'm doing with session info just looks like an application of that.
