### ISSUE TITLE
reprex keyboard shortcut?

### ISSUE THREAD

**Issue by njtierney** [jennybc/reprex#56]
I'm not sure if this is a double up of #28, but I was thinking it would be really nifty to make a keyboard shortcut, so you could highlight some code, and then do something like `Cmd + Shift + R` and it would copy the text, then run reprex?

Thank you for writing a package I use almost every day!

**Comment by jennybc** [comment]
Yes, I would like this myself!

The catch: I either need to have >1 addins and one of them is non-interactive and bound to a keyboard shortcut, while the other(s) are more interactive and gadget-y. Or addins need to know if they were invoked via keyboard shortcut or menu and be able to behave differently (which I've already posed as a question for @kevinushey).

I think, in either case, binding to a keyboard shortcut is up to the user, no? But reprex could make a standard recommendation.

**Comment by jennybc** [comment]
Interim solution: make it so that pressing "enter" is like clicking "Render".
