### ISSUE TITLE
Feature request: strip prompt from input

### ISSUE THREAD

**Issue by jasonmtroos** [jennybc/reprex#57]
If my R console contains this:

```
> x <- rnorm(10)
> mean(x)
[1] 0.4189699
```

And I copy the first two lines so that my clipboard contains the following character string:

```
"> x <- rnorm(10)
> mean(x)"
```

And I call `reprex()`, then I get this as my output:

``` r
> x <- rnorm(10)
> mean(x)
#> Error: <text>:1:1: unexpected '>'
#> 1: >
#>     ^
```

A nice feature here would be to automatically strip out values of

``` r
options("prompt")
#> $prompt
#> [1] "> "
```

when they appear at the start of a newline.

Cool package!

**Comment by jennybc** [comment]
This doesn't come up for me, I think, because I'm always composing in an editor and would copy prompt-free code from there.

But I see what you mean! I can't think of any legitimate reason to have leading prompts in `reprex()` input so I suppose I can automatically strip. I'll do this ... only question is whether to do for clipboard input only or just across the board.

**Comment by jennybc** [comment]
Because sometimes I am forced to work with "reprex" code other people have posted somewhere that includes the prompts.

**Comment by jasonmtroos** [comment]
Then maybe an optional parameter `strip_prompt = NULL` that can accept a string? For me the use cases probably involve emailing students or generating code to be inserted into non-markdown slides. These are certainly edge cases.

**Comment by jennybc** [comment]
Note to self: maybe I should trigger reading from clipboard via default behaviour of the `input` argument (instead of when both `x` and `input` are `NULL`). Then I could enact prompt stripping there for all non-expression input?

**Comment by jennybc** [comment]
> For me the use cases probably involve emailing students or generating code to be inserted into non-markdown slides. These are certainly edge cases.

Now here you seem to be talking about **output**, not handling of **input**. Do you want to add the prompt to your `reprex()` output? Because I can show you how to do that.

**Comment by jennybc** [comment]
If you want to make it look like an R transcript, you can override the default chunk options like so:

This input:

``` r
reprex({
  x <- 1:4
  y <- 2:5
  x + y
}, opts_chunk = list(comment = NA, prompt = TRUE))
```

gives this output:

``` r
> x <- 1:4
> y <- 2:5
> x + y
[1] 3 5 7 9
```

**Comment by jasonmtroos** [comment]
Sorry for the confusion, that's not what I mean: I am indeed talking about handling of input. What I mean is that I am sometimes working interactively in the command window and need to just copy the last few lines I executed. This sometimes happens when emailing a student (e.g. to make sure a code snippet actually executes as expected before sending)...

**Comment by jennybc** [comment]
OK got it.

**Comment by jasonmtroos** [comment]
Thanks, works great!
