### ISSUE TITLE
~~Addin~~ extremely slow (perhaps just windows?) - add some kind of "busy" feedback?

### ISSUE THREAD

**Issue by daattali** [jennybc/reprex#66]
I copied the following text to clipboard:

``` r
foo <- "bar"
```

Then opened the addin and clicked on "Render". It takes 4-6 seconds until the modal shows up. I have no idea if something is happening or not. If I click the render button again any time in those 5 seconds, it errors out. Would be good to either show a "working" message, or just disable the render button after pressing it

rstudio 1.1.39

**Comment by jennybc** [comment]
Can you compare to doing the same with just `reprex()`? I also created a branch with no modal but just the message, as you and I did (https://github.com/jennybc/reprex/tree/no-modal). Would you try that too? Where could it be spending 4-6 seconds?!

**Comment by daattali** [comment]
It's not because of the modal, it takes several seconds if I just run
`reprex()`

---
R-Shiny Consultant
http://deanattali.com/shiny

**Comment by jennybc** [comment]
So then it has nothing to do with the addin at all, right?

**Comment by daattali** [comment]
Correct. Did not know that initially. But the problem does extend into the
addin in the sense that it's easy to click the button multiple times
because you don't know it's processing

**Comment by jennybc** [comment]
Thanks to #85 there is at least a spinner now. 🙂

**Comment by daattali** [comment]
Woah this comment/commit is a gold mine! New profile picture, `rcall`, install-github.me - so many secrets
