### ISSUE TITLE
Facilitate image upload and embedding

### ISSUE THREAD

**Issue by npjc** [jennybc/reprex#8]
See my [so](http://stackoverflow.com/questions/32238729/axis-labels-that-are-ggplot2-objects-grobs) post that I attempted to make with `reprex(venue = "so")` but the path hardcoding of the outputted .pngs does not currently work and so I have to upload each image manually. I realize this is early -- but very neat so far!

**Comment by jennybc** [comment]
Thanks for trying it! So what you're really asking for is ... help uploading figs to, e.g., imgur and then using resulting link to embed, right? That's a good idea but I can't promise to do it fast. I wonder what the best place to host such images is ...

Some relevant links ...

https://blog.stackexchange.com/2010/08/new-image-upload-support/

https://cran.r-project.org/web/packages/imguR/

I get that imgur is the default place to host when uploading to SO manually but it's not clear that `reprex` would necessarily have to do the same, though that's a sensible opening position.

**Comment by jennybc** [comment]
cc @leeper

**Comment by leeper** [comment]
knitr also uploads to imgur by default, so it's a logical choice.

**Comment by jennybc** [comment]
Thanks @leeper.

**Comment by paternogbc** [comment]
@jennybc 

I have create a pull request with a possible solution. (commit: 9a39b2bfb33ae24abc61e0dfb0bbe6df8f270b64)
I have tested in my fork and worked fine. 
Cheers

**Comment by jennybc** [comment]
Thanks @paternogbc! I am starting my course in less than 2 days but will cycle back around to this soon. Just to get the link here, the associated PR seems be #15.

**Comment by paternogbc** [comment]
You welcome @jennybc.

Until now this single line addition worked on all examples I am working.
I will keep on tests and let you know if there is any problem.

All the best

**Comment by jennybc** [comment]
Done by @paternogbc via #15
