### ISSUE TITLE
Maybe some bits and pieces to pull in from the overflow package

### ISSUE THREAD

**Issue by mrdwab** [jennybc/reprex#9]
You can find the [overflow package here](https://github.com/mrdwab/overflow-mrdwab). Have not done much development on it in a while, but @richierocks had made some interesting contributions for the `soanswer` function. 

We've had clipboard issues too, but here's our implementation of [`readClip`](https://github.com/mrdwab/overflow-mrdwab/blob/master/R/readClip.R) and [`writeClip`](https://github.com/mrdwab/overflow-mrdwab/blob/master/R/writeClip.R).

**Comment by jennybc** [comment]
Thanks @mrdwab! Yes maybe some features could be integrated.  Long term I really think there should be a standalone clipboard mini-package that this package could them import. But today, in real life, I'd love to get clipboard functionality on other OSes within `reprex`.

I don't have physical access to a Windows computer and am being too lazy to set up something in the cloud and also fear it would not give me a faithful clipboard experience anyway. It would be better if someone who can test on a physical Windows box is checking things.

BTW `overflow` currently has no LICENSE. How could using `readClip` and `writeClip` work? Would you add a LICENSE and I grab some of the code? Or do you want to make a pull request?

**Comment by mdlincoln** [comment]
I've abstracted the OS X, Windows, and Linux versions of clipboard writing into just such a micro-package: [clipr](https://github.com/mdlincoln/clipr). It's super basic at the moment - it could probably use a `clear_clip()` command among other things, but maybe it'll be useful?

**Comment by jennybc** [comment]
Thanks @mdlincoln for starting `clipr`! This is a much needed thing. We should get other eyeballs on it. It would be truly awesome if it works as well as possible on lots of OSes, which I think requires actual humans on the OSes to be using it. I'm sure some automated testing is possible (and needed) but I bet this is an area where it's not a perfect solution.

I have concerns about LICENSEs. Neither `overflow` nor `clipr` has one, I think.

**Comment by mdlincoln** [comment]
1. Yes, there will be a bunch of annoying edge cases with system clipboards, so more eyes are a must! (I'm also just on OS X myself)
2. Re: LICENSE - both `overflow` and `clipr` specify GPL-3 in their respective `DESCRIPTION` files. I'm [following Hadley's guidance here](http://r-pkgs.had.co.nz/description.html#license).

**Comment by jennybc** [comment]
Sorry about the ill-informed no license comment. Duh, I was just looking for a LICENSE file, not reading the DESCRIPTION. I use MIT which forces you to write a two line LICENSE file.
